project:
  type: website

website:
  title: "Sukesh Perla"
  navbar:
    left:
      - about.qmd
    right:
      - icon: github
        href: https://github.com/hitchhiker3010
      - icon: twitter
        href: https://twitter.com/hitchhiker3010
      - icon: linkedin
        href: https://www.linkedin.com/in/sukesh-perla/
  google-analytics: "G-6Y1QVETG5N"
  search: false
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



